- name: "1.10 | PATCH | Ensure system-wide crypto policy is not legacy"
  shell: |
      update-crypto-policies --set "{{ crypto_policy }}"
      update-crypto-policies
  notify: change_requires_reboot
  when:
      - rule_1_10
      - crypto_policy|string not in system_wide_crypto_policy['stdout']
  tags:
      - level1-server
      - level1-workstation
      - automated
      - no system_is_ec2
      - patch
      - rule_1.10

- name: "1.11 | PATCH | Ensure system-wide crypto policy is FUTURE or FIPS"
  shell: |
      update-crypto-policies --set "{{ crypto_policy }}"
      update-crypto-policies
  notify: change_requires_reboot
  when:
      - rule_1_11
      - crypto_policy|string not in system_wide_crypto_policy['stdout']
  tags:
      - level1-server
      - level1-workstation
      - automated
      - no system_is_ec2
      - patch
      - rule_1.11
