---

- name: "1.2.1 | PATCH | Ensure Red Hat Subscription Manager connection is configured"
  redhat_subscription:
      state: present
      username: "{{ rh_sub_user }}"
      password: "{{ rh_sub_password }}"
      pool: "{{ rh_pool }}"
  when:
      - ansible_distribution == "RedHat"
      - rhnsd_required
      - rule_1_2_1
  tags:
      - level1-server
      - level1-workstation
      - manual
      - patch
      - rule_1.2.1
      - skip_ansible_lint  # Added as no_log still errors on ansible-lint

- name: 1.2.2 | PATCH | Disable the rhnsd Daemon
  command: /sbin/chkconfig rhnsd off
  ignore_errors: true
  changed_when: false
  when:
      - rule_1_2_2
  tags:
      - level2-server
      - level2-workstation
      - patch
      - rule_1.2.2

- name: "1.2.3 | PATCH | Ensure GPG keys are configured"
  block:
      - name: "1.2.3 | PATCH | Ensure GPG keys are configured"
        shell: "PKG=`rpm -qf {{ rpm_gpg_key }}` && rpm -q --queryformat \"%{PACKAGER} %{SIGPGP:pgpsig}\\n\" \"${PKG}\" | grep \"^{{ rpm_packager }}.*Key.ID.{{ rpm_key }}\""
        changed_when: false
  when:
      - rule_1_2_3
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_1.2.3

- name: "1.2.4| PATCH | Ensure gpgcheck is globally activated"
  block:
      - name: "1.2.4 | AUDIT | Ensure gpgcheck is globally activated | Find repos"
        find:
            paths: /etc/yum.repos.d
            patterns: "*.repo"
        register: yum_repos
        changed_when: false

      - name: "1.2.4 | PATCH | Ensure gpgcheck is globally activated | Update yum.repos"
        replace:
            name: "{{ item.path }}"
            regexp: "^gpgcheck=0"
            replace: "gpgcheck=1"
        with_items:
            - "{{ yum_repos.files }}"
        loop_control:
            label: "{{ item.path }}"
  when:
      - rule_1_2_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.2.4

- name: "1.2.5 | AUDIT | Ensure package manager repositories are configured"
  block:
      - name: "1.2.5 | AUDIT | Ensure package manager repositories are configured"
        shell: yum repolist
        changed_when: false
        register: repolist
        check_mode: false
        tags:
            - skip_ansible_lint

      - name: "1.2.5 | AUDIT | Ensure package manager repositories are configured"
        debug:
            msg:
                - "Please check against site policy repos listed below match expected:"
                - "{{ repolist.stdout_lines }}"
  when:
      - rule_1_2_5
  tags:
      - level1-server
      - level1-workstation
      - audit
      - rule_1.2.5
      - skip_ansible_lint
