---

- name: "5.3.1/5.3.2 | PATCH | Ensure custom authselect profile is used"
  block:
      - name: "5.3.1/5.3.2 | AUDIT | Ensure custom authselect profile is used | Gather profiles"
        shell: 'authselect current | grep "Profile ID: custom/"'
        failed_when: false
        changed_when: false
        check_mode: false
        register: 5_3_1/2_profiles

      - name: "5.3.1/5.3.2 | AUDIT | Ensure custom authselect profile is used | Show profiles"
        debug:
            msg:
                - "Below are the current custom profiles"
                - "{{ 5_3_1/2_profiles.stdout_lines }}"

      - name: "5.3.1/5.3.2 | PATCH | Ensure custom authselect profile is used | Create custom profiles"
        shell: authselect create-profile {{ authselect['custom_profile_name'] }} -b {{ authselect['default_file_to_copy'] }}
        when: authselect_custom_profile_create
  when:
      - rule_5_3_1/2
      - ansible_distribution_major_version == '8'

  tags:
      - level1-server
      - level1-workstation
      - manual
      - patch
      - authselect
      - rule_5.3.1
      - rule_5.3.2

- name: "5.3.3 | PATCH | Ensure authselect includes with-faillock"
  block:
      - name: "5.3.3 | AUDIT | Ensure authselect includes with-faillock | Gather profiles and enabled features"
        shell: "authselect current | grep with-faillock"
        failed_when: false
        changed_when: falses
        check_mode: false
        register: 5_3_3_profiles_faillock

      - name: "5.3.3 | AUDIT | Ensure authselect includes with-faillock| Show profiles"
        debug:
            msg:
                - "Below are the current custom profiles"
                - "{{ 5_3_3_profiles_faillock.stdout_lines }}"

      - name: "5.3.3 | PATCH | Ensure authselect includes with-faillock | Create custom profiles"
        shell: "authselect select custom/{{ authselect['custom_profile_name'] }} with-faillock"
        when: authselect_custom_profile_select
  when:
      - rule_5_3_3
      - ansible_distribution_major_version == '8'
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - authselect
      - rule_5.3.3