---

- name: "5.4.1 | PATCH | Ensure password creation requirements are configured"
  lineinfile:
      state: present
      dest: "/etc/security/pwquality.conf"
      regexp: '^{{ item.key }}'
      line: '{{ item.key }} = {{ item.value }}'
  with_items:
      - { key: 'minlen', value: '14' }
      - { key: 'minclass', value: '4' }
  when:
      - rule_5_4_1
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_5.4.1

- name: |
        "5.4.2 | PATCH | Ensure lockout for failed password attempts is configured
         5.4.3 | PATCH | Ensure password reuse is limited
         5.4.4 | PATCH | Ensure password hashing algorithm is SHA-512"
  block:
      - name: "5.4.2 | PATCH | Ensure lockout for failed password attempts is configured | Add deny count and unlock time for preauth"
        lineinfile:
            dest: "/etc/pam.d/{{ item }}"
            state: present
            line: "auth        required      pam_faillock.so preauth audit silent deny={{ pam_faillock.attempts }}{{ (pam_faillock.fail_for_root) | ternary(' even_deny_root ',' ') }}unlock_time={{ pam_faillock.unlock_time }}"
            insertafter: '^#?auth ?'
        loop:
            - "system-auth"
            - "password-auth"

      - name: "5.4.2 | PATCH | Ensure lockout for failed password attempts is configured | Add success and default settings to pam_unix.so"
        lineinfile:
            dest: "/etc/pam.d/{{ item }}"
            state: present
            line: "auth        [success=1 default=bad] pam_unix.so"
            insertafter: '^#?auth ?'
        loop:
            - "system-auth"
            - "password-auth"

      - name: "5.4.2 | PATCH | Ensure lockout for failed password attempts is configured | Add default, deny count, and unlock times for authfail"
        lineinfile:
            dest: "/etc/pam.d/{{ item }}"
            state: present
            line: "auth        [default=die] pam_faillock.so authfail audit deny={{ pam_faillock.attempts }}{{ (pam_faillock.fail_for_root) | ternary(' even_deny_root ',' ') }}unlock_time={{ pam_faillock.unlock_time }}"
            insertafter: '^#?auth ?'
        loop:
            - "system-auth"
            - "password-auth"

      - name: "5.4.2 | PATCH | Ensure lockout for failed password attempts is configured | Add deny count and unlock times to authsucc"
        lineinfile:
            dest: "/etc/pam.d/{{ item }}"
            state: present
            line: "auth        sufficient    pam_faillock.so authsucc audit deny={{ pam_faillock.attempts }}{{ (pam_faillock.fail_for_root) | ternary(' even_deny_root ',' ') }}unlock_time={{ pam_faillock.unlock_time }}"
            insertafter: '^#?auth ?'
        loop:
            - "system-auth"
            - "password-auth"

      - name: "5.4.2 | PATCH | Ensure lockout for failed password attempts is configured | Activate deny count and unlock times to failed password"
        lineinfile:
            dest: "/etc/pam.d/{{ item }}"
            state: present
            line: "account     required      pam_faillock.so"
            firstmatch: true
            regexp: '^\s*account\s+required\s+pam_faillock.so\s*'
            insertbefore: '^#?account ?'
        loop:
            - "system-auth"
            - "password-auth"

      - name: "5.4.3 | PATCH | Ensure password reuse is limited | add remember settings"
        lineinfile:
            dest: "/etc/pam.d/{{ item }}"
            state: present
            line: "password    required    pam_pwhistory.so remember={{ pam_faillock.remember }}"
            insertafter: '^#?password ?'
        loop:
            - "system-auth"
            - "password-auth"

      - name: "5.4.4 | PATCH | Ensure password hashing algorithm is SHA-512 | add sha512 settings"
        lineinfile:
            dest: "/etc/pam.d/{{ item }}"
            state: present
            line: "password    sufficient    pam_unix.so {{ pam_faillock.pwhash }} shadow nullok try_first_pass use_authtok"
            insertafter: '^#?password ?'
        loop:
            - "system-auth"
            - "password-auth"

      - name: |
              "5.4.2 | PATCH | Ensure lockout for failed password attempts is configured | Copy system/passowrd-auth to system/password-auth-local
               5.4.3 | PATCH | Ensure password reuse is limited | Copy system/password-auth to system/password-auth-local
               5.4.4 | PATCH | Ensure password hashing algorithm is SHA-512"

        copy:
            src: "/etc/pam.d/{{ item }}"
            dest: "/etc/pam.d/{{ item }}-local"
            remote_src: true
            owner: root
            group: root
            mode: '0644'
        loop:
            - "system-auth"
            - "password-auth"

      - name: |
              "5.4.2 | PATCH | Ensure lockout for failed password attempts is configured | Setup symbolic link
               5.4.3 | PATCH | Ensure password reuse is limited | Setup symbolic link"
        file:
            src: "/etc/pam.d/{{ item }}-local"
            dest: "/etc/pam.d/{{ item }}"
            state: link
            force: true
        loop:
            - "system-auth"
            - "password-auth"
  when:
      - rule_5_4_2
      - rule_5_4_3
      - rule_5_4_4
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_5.4.2
      - rule_5.4.3