---

- name: "2.2.2 | PATCH | Ensure X11 Server components are not installed"
  package:
      state: absent
      name:
          - "@X Window System"
          - "xorg-x11*"
  vars:
      ansible_python_interpreter: /bin/python2
  when:
      - not xwindows_required
      - rule_2_2_2
  tags:
      - level1-server
      - level1-workstation
      - xwindows
      - patch
      - rule_2.2.2

- name: "2.2.3 | PATCH | Ensure rsync is not installed or the rsyncd services are masked"
  block:
      - name: "2.2.3 | PATCH | Ensure rsync is not installed or the rsyncd services are masked | pkg removal"
        package:
            name: rsync
            state: absent
        vars:
            ansible_python_interpreter: /bin/python2

      - name: "2.2.3 | PATCH | Ensure rsync is not installed or the rsyncd services are masked | Mask "
        systemd:
            name: rsyncd
            masked: true
  when:
      - not rsyncd_server
      - not audit_content == 'git'  # Required by git for audit
      - "'rsync' in ansible_facts.packages"
      - rule_2_2_3
  tags:
      - level1-server
      - level1-workstation
      - rsync
      - services
      - patch
      - rule_2.2.3

- name: "2.2.4 | PATCH | Ensure Avahi Server is not installed | disabled"
  service:
      name: avahi-daemon
      state: stopped
      enabled: false
  when:
      - not avahi_server
      - "'avahi' in ansible_facts.packages"
      - rule_2_2_4
  tags:
      - level1-server
      - level1-workstation
      - avahi
      - services
      - patch
      - rule_2.2.4

- name: "2.2.5 | PATCH | Ensure net-snmp is not installed"
  package:
      name: net-snmp
      state: absent
  vars:
      ansible_python_interpreter: /bin/python2
  when:
      - not snmp_server
      - "'net-snmp' in ansible_facts.packages"
      - rule_2_2_5
  tags:
      - level1-server
      - level1-workstation
      - squid
      - services
      - patch
      - rule_2.2.5

- name: "2.2.6 | PATCH | Ensure HTTP Proxy server is not installed"
  package:
      name: squid
      state: absent
  vars:
      ansible_python_interpreter: /bin/python2
  when:
      - not squid_server
      - "'squid' in ansible_facts.packages"
      - rule_2_2_6
  tags:
      - level1-server
      - level1-workstation
      - squid
      - services
      - patch
      - rule_2.2.6

- name: "2.2.7 | PATCH | Ensure Samba server is not installed"
  package:
      name: samba
      state: absent
  vars:
      ansible_python_interpreter: /bin/python2
  when:
      - not smb_server
      - "'samba' in ansible_facts.packages"
      - rule_2_2_7
  tags:
      - level1-server
      - level1-workstation
      - samba
      - services
      - patch
      - rule_2.2.7

- name: "2.2.8 | PATCH | Ensure IMAP and POP3 server is not installed"
  package:
      name: dovecot
      state: absent
  vars:
      ansible_python_interpreter: /bin/python2
  when:
      - not dovecot_server
      - "'dovecot' in ansible_facts.packages"
      - rule_2_2_8
  tags:
      - level1-server
      - level1-workstation
      - dovecot
      - services
      - patch
      - rule_2.2.8

- name: "2.2.9 | PATCH | Ensure HTTP server is not installed"
  package:
      name: httpd
      state: absent
  vars:
      ansible_python_interpreter: /bin/python2
  when:
      - not httpd_server
      - "'httpd' in ansible_facts.packages"
      - rule_2_2_9
  tags:
      - level1-server
      - level1-workstation
      - httpd
      - services
      - patch
      - rule_2.2.9

- name: "2.2.10 | PATCH | Ensure FTP server is not installed"
  package:
      name: vsftpd
      state: absent
  vars:
      ansible_python_interpreter: /bin/python2
  when:
      - not vsftpd_server
      - "'vsftpd' in ansible_facts.packages"
      - rule_2_2_10
  tags:
      - level1-server
      - level1-workstation
      - ftp
      - services
      - patch
      - rule_2.2.10

- name: "2.2.11 | PATCH | Ensure DNS server is not installed"
  package:
      name: bind
      state: absent
  vars:
      ansible_python_interpreter: /bin/python2
  when:
      - not named_server
      - "'bind' in ansible_facts.packages"
      - rule_2_2_11
  tags:
      - level1-server
      - level1-workstation
      - dns
      - services
      - patch
      - rule_2.2.11

- name: "2.2.12 | PATCH | Ensure nfs-utils is not installed or the nfs-server service is masked"
  block:
      - name: "2.2.12 | PATCH | Ensure nfs-utils is not installed or the nfs-server service is masked | nfs-utils "
        package:
            name: nfs-utils
            state: absent
        vars:
            ansible_python_interpreter: /bin/python2
        when:
            - not nfs_rpc_server and not nfs_server

      - name: "2.2.12 | PATCH | Ensure nfs-utils is not installed or the nfs-server service is masked | nfs-server "
        systemd:
            name: nfs-server
            masked: true
        when:
            - nfs_rpc_server and not nfs_server
  when:
      - "'nfs-utils' in ansible_facts.packages"
      - rule_2_2_12
  tags:
      - level1-server
      - level1-workstation
      - nfs
      - services
      - patch
      - rule_2.2.12

- name: "2.2.13 | PATCH | Ensure rpcbind is not installed or the rpcbind services are masked"
  block:
      - name: "2.2.13 | PATCH | Ensure rpcbind is not installed or the rpcbind services are masked | rpcbind"
        package:
            name: rpcbind
            state: absent
        vars:
            ansible_python_interpreter: /bin/python2
        when:
            - not nfs_rpc_server and not rpc_server

      - name: "2.2.13 | PATCH | Ensure rpcbind is not installed or the rpcbind services are masked | rpcbind-server"
        systemd:
            name: rpcbind
            masked: true
        when:
            - nfs_rpc_server and not rpc_server

      - name: "2.2.13 | PATCH | Ensure rpcbind is not installed or the rpcbind services are masked | rpcbind-server"
        systemd:
            name: rpcbind.socket
            masked: true
        when:
            - nfs_rpc_server and not rpc_server
  when:
      - "'rpcbind' in ansible_facts.packages"
      - rule_2_2_13
  tags:
      - level1-server
      - level1-workstation
      - rpc
      - services
      - patch
      - rule_2.2.13

- name: "2.2.14 | PATCH | Ensure LDAP server is not installed"
  package:
      name: openldap-servers
      state: absent
  vars:
      ansible_python_interpreter: /bin/python2
  when:
      - not ldap_server
      - "'openldap-servers' in ansible_facts.packages"
      - rule_2_2_14
  tags:
      - level1-server
      - level1-workstation
      - ldap
      - services
      - patch
      - rule_2.2.14

- name: "2.2.15 | PATCH | Ensure DHCP Server is not installed"
  package:
      name: dhcp
      state: absent
  vars:
      ansible_python_interpreter: /bin/python2
  when:
      - not dhcp_server
      - "'dhcp' in ansible_facts.packages"
      - rule_2_2_15
  tags:
      - level1-server
      - level1-workstation
      - dhcp
      - services
      - patch
      - rule_2.2.15


- name: "2.2.16 | PATCH | Ensure CUPS is not installed"
  package:
      name: cups
      state: absent
  vars:
      ansible_python_interpreter: /bin/python2
  when:
      - not cups_server
      - "'cups' in ansible_facts.packages"
      - rule_2_2_16
  tags:
      - level1-server
      - level1-workstation
      - cups
      - services
      - patch
      - rule_2.2.16

- name: "2.2.17 | PATCH | Ensure NIS server is not installed"
  package:
      name: ypserv
      state: absent
  vars:
      ansible_python_interpreter: /bin/python2
  when:
      - not nis_server
      - "'ypserv' in ansible_facts.packages"
      - rule_2_2_17
  tags:
      - level1-server
      - level1-workstation
      - nis
      - services
      - patch
      - rule_2.2.17

- name: "2.2.18 | PATCH | Ensure mail transfer agent is configured for local-only mode"
  lineinfile:
      dest: /etc/postfix/main.cf
      regexp: "^(#)?inet_interfaces"
      line: "inet_interfaces = loopback-only"
  notify: restart postfix
  when:
      - not is_mail_server
      - "'postfix' in ansible_facts.packages"
      - rule_2_2_18
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.2.18