---

- name: "2.3.1 | PATCH | Ensure NIS client is not installed"
  package:
      name: ypbind
      state: absent
  vars:
      ansible_python_interpreter: /bin/python2
  when:
      - not ypbind_required
      - "'ypbind' in ansible_facts.packages"
      - rule_2_3_1
  tags:
      - level1-server
      - level1-workstation
      - nis
      - patch
      - rule_2.3.1

- name: "2.3.2 | PATCH | Ensure telnet client is not installed"
  package:
      name: telnet
      state: absent
  vars:
      ansible_python_interpreter: /bin/python2
  when:
      - "'telnet' in ansible_facts.packages"
      - not telnet_required
      - rule_2_3_2
  tags:
      - level1-server
      - level1-workstation
      - telnet
      - patch
      - rule_2.3.2

- name: "2.3.3 | PATCH | Ensure LDAP client is not installed"
  package:
      name: openldap-clients
      state: absent
  vars:
      ansible_python_interpreter: /bin/python2
  when:
      - not openldap_clients_required
      - "'openldap-clients' in ansible_facts.packages"
      - rule_2_3_3
  tags:
      - level1-server
      - level1-workstation
      - ldap_client
      - patch
      - rule_2.3.3