---
- name: "3.1.1 | PATCH | Ensure IP forwarding is disabled | IPv4"
  block:
      - name: "3.1.1 | PATCH | Ensure IP forwarding is disabled | IPv4"
        sysctl:
            name: net.ipv4.ip_forward
            value: '0'
            state: present
            reload: true
            ignoreerrors: true
        notify:
            - sysctl flush ipv4 route table

      - name: "3.1.1 | PATCH | Ensure IP forwarding is disabled IPv6"
        sysctl:
            name: net.ipv6.conf.all.forwarding
            value: '0'
            state: present
            reload: true
            ignoreerrors: true
        notify:
            - sysctl flush ipv6 route table
        when:
            - ipv6_required
  when:
      - not is_router
      - rule_3_1_1
  tags:
      - level1-server
      - level1-workstation
      - sysctl
      - patch
      - rule_3.1.1

- name: "3.1.2 | PATCH | Ensure packet redirect sending is disabled"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: true
      state: present
      reload: true
      ignoreerrors: true
  with_items:
      - { name: net.ipv4.conf.all.send_redirects, value: 0 }
      - { name: net.ipv4.conf.default.send_redirects, value: 0 }
  notify:
      - sysctl flush ipv4 route table
  when:
      - not is_router
      - rule_3_1_2
  tags:
      - level1-server
      - level1-workstation
      - sysctl
      - patch
      - rule_3.1.2
