---

- name: "5.2.1 | PATCH | Ensure permissions on /etc/ssh/sshd_config are configured"
  file:
      dest: /etc/ssh/sshd_config
      state: file
      owner: root
      group: root
      mode: 0600
  when:
      - rule_5_2_1
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.2.1

- name: "5.2.2 | PATCH | Ensure SSH access is limited"
  block:
      - name: "5.2.2 | PATCH | Ensure SSH access is limited | Add line to sshd_config for allowusers"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: "^AllowUsers"
            insertbefore: "# Accept locale-related environment variables"
            line: AllowUsers {{ sshd['allowusers'] }}
            validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
        notify:
            - restart sshd
        when:
            - "sshd['allowusers']|default('') | length > 0"

      - name: "5.2.2 | PATCH | Ensure SSH access is limited | Add line to sshd_config for allowgroups"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: "^AllowGroups"
            insertbefore: "# Accept locale-related environment variables"
            line: AllowGroups {{ sshd['allowgroups'] }}
            validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
        notify:
            - restart sshd
        when:
            - "sshd['allowgroups']|default('') | length > 0"

      - name: "5.2.2 | PATCH | Ensure SSH access is limited | Add line to sshd_config for denyusers"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: "^DenyUsers"
            insertbefore: "# Accept locale-related environment variables"
            line: DenyUsers {{ sshd['denyusers'] }}
            validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
        notify:
            - restart sshd
        when:
            - "sshd['denyusers']|default('') | length > 0"

      - name: "5.2.2 | PATCH | Ensure SSH access is limited | Add line to sshd_config for denygroups"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: "^DenyGroups"
            insertbefore: "# Accept locale-related environment variables"
            line: DenyGroups {{ sshd['denygroups'] }}
            validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
        notify:
            - restart sshd
        when:
            - "sshd['denygroups']|default('') | length > 0"
  when:
      - rule_5_2_2
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.2.2

- name: "5.2.3 | PATCH | Ensure permissions on SSH private host key files are configured"
  block:
      - name: "5.2.3 | AUDIT | Ensure permissions on SSH private host key files are configured"
        find:
            paths:
                - /etc/ssh
            patterns: 'ssh_host_*_key'
            recurse: true
            file_type: any
        register: rhel_5_2_3_priv_results

      - name: "5.2.3 | AUDIT | Ensure permissions on SSH private host key files are configured"
        file:
            path: "{{ item.path }}"
            owner: root
            group: root
            mode: 0600
        loop: "{{ rhel_5_2_3_priv_results.files }}"
        loop_control:
            label: "{{ item.path }}"
  when:
      - rule_5_2_3
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.2.3

- name: "5.2.4 | PATCH | Ensure permissions on SSH public host key files are configured"
  block:
      - name: "5.2.4 | AUDIT | Ensure permissions on SSH public host key files are configured"
        find:
            paths:
                - /etc/ssh
            patterns: 'ssh_host_*_key'
            recurse: true
            file_type: any
        register: rhel_5_2_4_pub_results

      - name: "5.2.4 | AUDIT | Ensure permissions on SSH public host key files are configured"
        file:
            path: "{{ item.path }}"
            owner: root
            group: root
            mode: 0600
        loop: "{{ rhel_5_2_4_pub_results.files }}"
        loop_control:
            label: "{{ item.path }}"
  when:
      - rule_5_2_4
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.2.4

- name: "5.2.5 | PATCH | Ensure SSH LogLevel is appropriate"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^#LogLevel|^LogLevel"
      line: 'LogLevel {{ ssh_loglevel }}'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rule_5_2_5
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.2.5

- name: "5.2.6 | PATCH | Ensure SSH X11 forwarding is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^#X11Forwarding|^X11Forwarding"
      line: 'X11Forwarding no'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rule_5_2_6
  tags:
      - level2-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.2.6

- name: "5.2.7 | PATCH | Ensure SSH MaxAuthTries is set to 4 or less"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^(#)?MaxAuthTries \d'
      line: 'MaxAuthTries 4'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rule_5_2_7
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.2.7

- name: "5.2.8 | PATCH | Ensure SSH IgnoreRhosts is enabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^#IgnoreRhosts|^IgnoreRhosts"
      line: 'IgnoreRhosts yes'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rule_5_2_8
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.2.8

- name: "5.2.9 | PATCH | Ensure SSH HostbasedAuthentication is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^#HostbasedAuthentication|^HostbasedAuthentication"
      line: 'HostbasedAuthentication no'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rule_5_2_9
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.2.9

- name: "5.2.10 | PATCH | Ensure SSH root login is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^#PermitRootLogin|^PermitRootLogin"
      line: 'PermitRootLogin no'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rule_5_2_10
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.2.10

- name: "5.2.11 | PATCH | Ensure SSH PermitEmptyPasswords is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^#PermitEmptyPasswords|^PermitEmptyPasswords"
      line: 'PermitEmptyPasswords no'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rule_5_2_11
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.2.11

- name: "5.2.12 | PATCH | Ensure SSH PermitUserEnvironment is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^#PermitUserEnvironment|^PermitUserEnvironment"
      line: 'PermitUserEnvironment no'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rule_5_2_12
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.2.12

- name: "5.2.13 | PATCH | Ensure SSH Idle Timeout Interval is configured"
  block:
      - name: "5.2.13 | PATCH | Ensure SSH Idle Timeout Interval is configured | Add line in sshd_config for ClientAliveInterval"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: "^#ClientAliveInterval|^ClientAliveInterval"
            line: "ClientAliveInterval {{ sshd['clientaliveinterval'] }}"
            validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
        notify:
            - restart sshd

      - name: "5.2.13 | PATCH | Ensure SSH Idle Timeout Interval is configured | Ensure SSH ClientAliveCountMax set to <= 3"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: "^#ClientAliveCountMax|^ClientAliveCountMax"
            line: "ClientAliveCountMax {{ sshd['clientalivecountmax'] }}"
            validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
        notify:
            - restart sshd
  when:
      - rule_5_2_13
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.2.13

- name: "5.2.14 | PATCH | Ensure SSH LoginGraceTime is set to one minute or less"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^#LoginGraceTime|^LoginGraceTime"
      line: "LoginGraceTime {{ sshd['logingracetime'] }}"
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rule_5_2_14
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.2.14

- name: "5.2.15 | PATCH | Ensure SSH warning banner is configured"
  lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^Banner ((?!/etc/issue.net$)).*$'
      line: "{{ item.line | default (omit) }}"
      insertafter: "{{ item.after | default(omit) }}"
      state: "{{ item.state }}"
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  with_items:
      - { state: absent }
      - { state: present, line: 'Banner /etc/issue.net', after: '#Banner none' }
  notify:
      - restart sshd
  when:
      - rule_5_2_15
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.2.15

- name: "5.2.16 | PATCH | Ensure SSH PAM is enabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^#UsePAM|^UsePAM"
      line: 'UsePAM yes'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rule_5_2_16
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.2.16

- name: "5.2.17 | PATCH | Ensure SSH AllowTcpForwarding is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^#AllowTcpForwarding|^AllowTcpForwarding"
      line: 'AllowTcpForwarding no'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rule_5_2_17
  tags:
      - level2-server
      - level2-workstation
      - patch
      - ssh
      - rule_5.2.17

- name: "5.2.18 | PATCH | Ensure SSH MaxStartups is configured"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^#MaxStartups|^MaxStartups"
      line: 'MaxStartups 10:30:60'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rule_5_2_18
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.2.18

- name: "5.2.19 | PATCH | Ensure SSH MaxSessions is limited"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^#MaxSessions|^MaxSessions"
      line: 'MaxSessions {{ ssh_maxsessions }}'
      validate: /usr/sbin/sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" -f %s
  notify:
      - restart sshd
  when:
      - rule_5_2_19
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ssh
      - rule_5.2.19

- name: "5.2.20 | PATCH | Ensure system-wide crypto policy is not over-ridden"
  block:
      - name: "5.2.20 | AUDIT | Ensure system-wide crypto policy is not over-ridden"
        shell: grep -i '^\s*CRYPTO_POLICY=' /etc/sysconfig/sshd
        failed_when: ( crypto_policy_override.rc not in [ 0, 1 ] )
        changed_when: false
        register: crypto_policy_override

      - name: "5.2.20 | PATCH | Ensure system-wide crypto policy is not over-ridden"
        shell: sed -ri "s/^\s*(CRYPTO_POLICY\s*=.*)$/# \1/" /etc/sysconfig/sshd
        notify: restart sshd
        when:
            - crypto_policy_override.stdout | length > 0
  when:
      - rule_5_2_20
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - ssh
      - rule_5.2.20
