---

- name: "5.6 | AUDIT | Ensure root login is restricted to system console "
  block:
      - name: "5.6 | AUDIT | Ensure root login is restricted to system console"
        command: cat /etc/securetty
        changed_when: false
        check_mode: false
        register: rhel_5_6_audit

      - name: "5.6 | AUDIT | Ensure root login is restricted to system console"
        debug:
            msg:
                - "These are the consoles with root login access, please review:"
                - "{{ rhel_5_6_audit.stdout_lines }}"
  when:
      - rule_5_6
  tags:
      - level1-server
      - level1-workstation
      - audit
      - rule_5.6