---


- name: "3.4.4.1.1 | PATCH | Ensure iptables default deny firewall policy"
  block:
      - name: "3.4.4.1.1 | PATCH | Ensure iptables default deny firewall policy | Configure SSH to be allowed in"
        iptables:
            chain: INPUT
            protocol: tcp
            destination_port: 22
            jump: ACCEPT
            ctstate: 'NEW,ESTABLISHED'

      - name: "3.4.4.1.1 | PATCH | Ensure iptables default deny firewall policy | Configure SSH to be allowed out"
        iptables:
            chain: OUTPUT
            protocol: tcp
            source_port: 22
            jump: ACCEPT
            ctstate: 'NEW,ESTABLISHED'

      - name: "3.4.4.1.1 | PATCH | Ensure iptables default deny firewall policy | Enable apt traffic"
        iptables:
            chain: INPUT
            ctstate: 'ESTABLISHED'
            jump: ACCEPT

      - name: "3.4.4.1.1 | PATCH | Ensure iptables default deny firewall policy | Set drop items"
        iptables:
            policy: DROP
            chain: "{{ item }}"
        with_items:
            - INPUT
            - FORWARD
            - OUTPUT
  when:
      - rule_3_4_4_1_1
      - not system_is_ec2
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.4.4.1.1
      - iptables


- name: "3.4.4.1.2 | PATCH | Ensure iptables loopback traffic is configured"
  block:
      - name: "3.4.4.1.2 | PATCH | Ensure iptables loopback traffic is configured | INPUT loopback ACCEPT"
        iptables:
            action: append
            chain: INPUT
            in_interface: lo
            jump: ACCEPT

      - name: "3.4.4.1.2 | PATCH | Ensure iptables loopback traffic is configured | OUTPUT loopback ACCEPT"
        iptables:
            action: append
            chain: OUTPUT
            out_interface: lo
            jump: ACCEPT

      - name: "3.4.4.1.2 | PATCH | Ensure iptables loopback traffic is configured | OUTPUT loopback ACCEPT"
        iptables:
            action: append
            chain: INPUT
            source: 127.0.0.0/8
            jump: DROP
  when:
      - rule_3_4_4_1_2
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.4.4.1.2
      - iptables

- name: "3.4.4.1.3 | PATCH | Ensure iptables outbound and established connections are configured"
  iptables:
      action: append
      chain: '{{ item.chain }}'
      protocol: '{{ item.protocol }}'
      match: state
      ctstate: '{{ item.ctstate }}'
      jump: ACCEPT
  with_items:
      - { chain: OUTPUT, protocol: tcp, ctstate: 'NEW,ESTABLISHED' }
      - { chain: OUTPUT, protocol: udp, ctstate: 'NEW,ESTABLISHED' }
      - { chain: OUTPUT, protocol: icmp, ctstate: 'NEW,ESTABLISHED' }
      - { chain: INPUT, protocol: tcp, ctstate: 'ESTABLISHED' }
      - { chain: INPUT, protocol: udp, ctstate: 'ESTABLISHED' }
      - { chain: INPUT, protocol: icmp, ctstate: 'ESTABLISHED' }
  when:
      - rule_3_4_4_1_3
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_3.4.4.1.3
      - iptables

- name: "3.4.4.1.4 | AUDIT | Ensure iptables firewall rules exist for all open ports"
  block:
      - name: "3.4.4.1.4 | AUDIT | Ensure iptables firewall rules exist for all open ports | Get list of open ports"
        command: ss -4tuln
        changed_when: false
        failed_when: false
        check_mode: false
        cis_: cis_3_4_4_1_4_open_ports

      - name: "3.4.4.1.4 | AUDIT | Ensure iptables firewall rules exist for all open ports | Get list of rules"
        command: iptables -L INPUT -v -n
        changed_when: false
        failed_when: false
        check_mode: false
        register: cis_3_4_4_1_4_current_rules

      - name: "3.4.4.1.4 | AUDIT | Ensure iptables firewall rules exist for all open ports | Alert about settings"
        debug:
            msg:
                - "ALERT!!!!Below is the list the open ports and current rules"
                - "Please create a rule for any open port that does not have a current rule"
                - "Open Ports:"
                - "{{ cis_3_4_4_1_4_open_ports.stdout_lines }}"
                - "Current Rules:"
                - "{{ cis_3_4_4_1_4_current_rules.stdout_lines }}"
  when:
      - rule_3_4_4_1_4
  tags:
      - level1-server
      - level1-workstation
      - audit
      - rule_3.4.4.1.4
      - iptables
